const ADD_PROFILE = 'ADD_PROFILE';
const REMOVE_PROFILE = 'REMOVE_PROFILE';
const EDIT_PROFILE = 'EDIT_PROFILE';
const SET_OPTIONS = 'SET_OPTIONS';

export { ADD_PROFILE, REMOVE_PROFILE, EDIT_PROFILE, SET_OPTIONS };
